/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Ykfk0Bqz52s
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import Link from 'next/link'
import Image from 'next/image'
import { SVG } from '@/components/svg'
import { Button } from '@/components/ui/button'
import { buttonVariants } from '@/components/ui/button'
import { SheetTrigger, SheetContent, Sheet } from '@/components/ui/sheet'
import {
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenu,
} from '@/components/ui/navigation-menu'
import { cn } from '@/lib/utils'
import { Icons } from './icons'
import { siteConfig } from '@/config/site'
import { ModeToggle } from '@/components/ui/mode-toggle'
import logo from '@/app/logo.png'

function HeaderNavItem({ href, children }) {
  return (
    <Link
      className="inline-flex h-9 items-center justify-center rounded-md px-4 py-2 text-xl font-normal transition-colors hover:cursor-pointer  disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-950"
      href={href}
    >
      {children}
    </Link>
  )
}
export function SiteHeader() {
  return (
    <header className="flex items-center justify-between px-4 py-3 md:py-4">
      <Link className="flex w-[200px] items-center gap-2" href="/">
        <Image src={logo} alt="Hypercube tesseract" className="h-10 w-10" />
        <span className="sr-only">Tesser network</span>
      </Link>
      <NavigationMenu className="hidden md:flex">
        <NavigationMenuList>
          <NavigationMenuLink asChild>
            <HeaderNavItem href={'/'}>/Home</HeaderNavItem>
          </NavigationMenuLink>
          <NavigationMenuLink asChild>
            <HeaderNavItem href={'/blog'}>/Blog</HeaderNavItem>
          </NavigationMenuLink>
        </NavigationMenuList>
      </NavigationMenu>
      <nav className="flex flex-1 items-center justify-end md:flex-none">
        <div className="mr-8 flex">
          <Link
            className="flex min-w-28 justify-center rounded-full border border-black px-3 py-1 text-center font-medium hover:bg-muted"
            rel="noreferrer"
            href="/vision"
          >
            Our Vision
          </Link>
        </div>
        <nav className="flex items-center">
          <Link href={siteConfig.links.github} target="_blank" rel="noreferrer">
            <div
              className={cn(
                buttonVariants({
                  variant: 'ghost',
                }),
                'w-9 px-0',
              )}
            >
              <Icons.gitHub className="h-6 w-6 fill-current" />
              <span className="sr-only">GitHub</span>
            </div>
          </Link>
          <Link
            href={siteConfig.links.twitter}
            target="_blank"
            rel="noreferrer"
          >
            <div
              className={cn(
                buttonVariants({
                  variant: 'ghost',
                }),
                'w-9 px-0',
              )}
            >
              <Icons.twitter className="h-5 w-5 fill-current" />
              <span className="sr-only">Twitter</span>
            </div>
          </Link>
          {/*<ModeToggle />*/}
        </nav>
      </nav>
      <Sheet>
        <SheetTrigger asChild>
          <Button className="md:hidden" size="icon" variant="outline">
            <MenuIcon className="h-6 w-6" />
            <span className="sr-only">Toggle navigation menu</span>
          </Button>
        </SheetTrigger>
        <SheetContent className="bg-gray-950 p-6 text-gray-50 md:hidden">
          <div className="flex flex-col gap-6">
            <Link
              className=" font-medium underline-offset-4 hover:underline"
              href="/"
            >
              /Home
            </Link>
            <Link
              className="font-medium underline-offset-4 hover:underline"
              href="/blog"
            >
              /Blog
            </Link>
          </div>
        </SheetContent>
      </Sheet>
    </header>
  )
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}
